/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pages.DeliveryRunner;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author vreesa
 */
public class DRmenu extends javax.swing.JFrame {

    /**
     * Creates new form DRmenu
     */
    public DRmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewTaskHistorybtn = new javax.swing.JButton();
        ViewAvailableTaskbtn = new javax.swing.JButton();
        ViewCurrentTaskbtn = new javax.swing.JButton();
        ViewCustReviewbtn = new javax.swing.JButton();
        UpdateTaskStatusbtn = new javax.swing.JButton();
        RevDashbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));

        ViewTaskHistorybtn.setBackground(new java.awt.Color(225, 237, 243));
        ViewTaskHistorybtn.setFont(new java.awt.Font("STIX Two Text", 1, 13)); // NOI18N
        ViewTaskHistorybtn.setForeground(new java.awt.Color(42, 49, 129));
        ViewTaskHistorybtn.setText("view task history");
        ViewTaskHistorybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTaskHistorybtnActionPerformed(evt);
            }
        });

        ViewAvailableTaskbtn.setBackground(new java.awt.Color(225, 237, 243));
        ViewAvailableTaskbtn.setFont(new java.awt.Font("STIX Two Text", 1, 13)); // NOI18N
        ViewAvailableTaskbtn.setForeground(new java.awt.Color(42, 49, 129));
        ViewAvailableTaskbtn.setText("view available tasks");
        ViewAvailableTaskbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAvailableTaskbtnActionPerformed(evt);
            }
        });

        ViewCurrentTaskbtn.setBackground(new java.awt.Color(225, 237, 243));
        ViewCurrentTaskbtn.setFont(new java.awt.Font("STIX Two Text", 1, 13)); // NOI18N
        ViewCurrentTaskbtn.setForeground(new java.awt.Color(42, 49, 129));
        ViewCurrentTaskbtn.setText("view current task");
        ViewCurrentTaskbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCurrentTaskbtnActionPerformed(evt);
            }
        });

        ViewCustReviewbtn.setBackground(new java.awt.Color(225, 237, 243));
        ViewCustReviewbtn.setFont(new java.awt.Font("STIX Two Text", 1, 13)); // NOI18N
        ViewCustReviewbtn.setForeground(new java.awt.Color(42, 49, 129));
        ViewCustReviewbtn.setText("view customer review");
        ViewCustReviewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCustReviewbtnActionPerformed(evt);
            }
        });

        UpdateTaskStatusbtn.setBackground(new java.awt.Color(225, 237, 243));
        UpdateTaskStatusbtn.setFont(new java.awt.Font("STIX Two Text", 1, 13)); // NOI18N
        UpdateTaskStatusbtn.setForeground(new java.awt.Color(42, 49, 129));
        UpdateTaskStatusbtn.setText("update task status");
        UpdateTaskStatusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateTaskStatusbtnActionPerformed(evt);
            }
        });

        RevDashbtn.setBackground(new java.awt.Color(225, 237, 243));
        RevDashbtn.setFont(new java.awt.Font("STIX Two Text", 1, 13)); // NOI18N
        RevDashbtn.setForeground(new java.awt.Color(42, 49, 129));
        RevDashbtn.setText("revenue dashboard");
        RevDashbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevDashbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("STIX Two Text", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(42, 49, 129));
        jLabel1.setText("DELIVERY RUNNER DASHBOARD: ");

        jScrollPane1.setViewportView(jTextPane1);

        jButton1.setBackground(new java.awt.Color(225, 237, 243));
        jButton1.setFont(new java.awt.Font("Songti TC", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(42, 49, 129));
        jButton1.setText("exit");
        jButton1.setAlignmentY(0.0F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewCustReviewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewCurrentTaskbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewAvailableTaskbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateTaskStatusbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewTaskHistorybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RevDashbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {RevDashbtn, UpdateTaskStatusbtn, ViewAvailableTaskbtn, ViewCurrentTaskbtn, ViewCustReviewbtn, ViewTaskHistorybtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(ViewAvailableTaskbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewCurrentTaskbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateTaskStatusbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewTaskHistorybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewCustReviewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RevDashbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {RevDashbtn, UpdateTaskStatusbtn, ViewAvailableTaskbtn, ViewCurrentTaskbtn, ViewCustReviewbtn, ViewTaskHistorybtn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewTaskHistorybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTaskHistorybtnActionPerformed
        this.dispose();
        new TaskHistory().setVisible(true); //open another form
        
// TODO add your handling code here:
    }//GEN-LAST:event_ViewTaskHistorybtnActionPerformed

    private void ViewCurrentTaskbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCurrentTaskbtnActionPerformed
        this.dispose();
        new CurrentTask().setVisible(true); //open another form
    }//GEN-LAST:event_ViewCurrentTaskbtnActionPerformed

    private void ViewCustReviewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCustReviewbtnActionPerformed
        this.dispose();
        new CustReview().setVisible(true); //open another form
    }//GEN-LAST:event_ViewCustReviewbtnActionPerformed

    private void UpdateTaskStatusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateTaskStatusbtnActionPerformed
        this.dispose();
        new UpdateStatus().setVisible(true); //open another form     
// TODO add your handling code here:
    }//GEN-LAST:event_UpdateTaskStatusbtnActionPerformed

    private void RevDashbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevDashbtnActionPerformed
        this.dispose();
        new RevenueDash().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_RevDashbtnActionPerformed

    private void ViewAvailableTaskbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAvailableTaskbtnActionPerformed
        this.dispose();
        new ChooseTasks().setVisible(true); //open another form

    }//GEN-LAST:event_ViewAvailableTaskbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DRmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DRmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DRmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DRmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DRmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RevDashbtn;
    private javax.swing.JButton UpdateTaskStatusbtn;
    private javax.swing.JButton ViewAvailableTaskbtn;
    private javax.swing.JButton ViewCurrentTaskbtn;
    private javax.swing.JButton ViewCustReviewbtn;
    private javax.swing.JButton ViewTaskHistorybtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
