package Pages.Admin;
import FileManager.*;
import Models.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class UpdateUserFrame extends javax.swing.JFrame {
    
    private Admin admin;
    
    public UpdateUserFrame() {
        this.admin = (Admin) CurrentUser.getLoggedInUser();
        initComponents();
        addUserSelectionListener();
        addSearchFieldListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Admin = new javax.swing.JLabel();
        UserPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        selectedUserField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        newUsernametxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        newPasswordtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        newBalance = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(470, 390));

        MainPanel.setPreferredSize(new java.awt.Dimension(470, 400));
        MainPanel.setRequestFocusEnabled(false);
        MainPanel.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(470, 35));

        Admin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Admin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Admin.setText("Admin Dashboard");
        Admin.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Admin.setPreferredSize(new java.awt.Dimension(400, 25));
        Admin.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Admin, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        MainPanel.add(jPanel2, java.awt.BorderLayout.NORTH);

        UserPanel.setPreferredSize(new java.awt.Dimension(470, 215));

        jLabel6.setText("Search");

        searchField.setPreferredSize(new java.awt.Dimension(100, 25));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Users");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(180, 200));

        jScrollPane1.setViewportView(userList);

        jLabel2.setText("Selected User");

        selectedUserField.setPreferredSize(new java.awt.Dimension(140, 25));
        selectedUserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedUserFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Username");

        newUsernametxt.setPreferredSize(new java.awt.Dimension(100, 25));

        jLabel4.setText("Password");

        newPasswordtxt.setPreferredSize(new java.awt.Dimension(100, 25));

        jLabel5.setText("Balance");

        newBalance.setPreferredSize(new java.awt.Dimension(100, 25));

        updateButton.setText("Update");
        updateButton.setPreferredSize(new java.awt.Dimension(80, 25));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        returnButton.setText("Return");
        returnButton.setPreferredSize(new java.awt.Dimension(80, 25));
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserPanelLayout = new javax.swing.GroupLayout(UserPanel);
        UserPanel.setLayout(UserPanelLayout);
        UserPanelLayout.setHorizontalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectedUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addGroup(UserPanelLayout.createSequentialGroup()
                        .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(newUsernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newPasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        UserPanelLayout.setVerticalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectedUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UserPanelLayout.createSequentialGroup()
                        .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newUsernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        MainPanel.add(UserPanel, java.awt.BorderLayout.LINE_START);

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        
    }//GEN-LAST:event_searchFieldActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        new AdminFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        
        String selectedValue = userList.getSelectedValue(); // Get Selected User String
        if (selectedValue == null) {
            JOptionPane.showMessageDialog(this, "Please select a user to update.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String uid = selectedValue.split(" - ")[0];
        String newUsername = newUsernametxt.getText();
        String newPassword = newPasswordtxt.getText();
        String balanceString = newBalance.getText();
        double newbalance;
        
        try {
            newbalance = Double.parseDouble(balanceString);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid balance value.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        ArrayList<User> users = FileManager.loadUsers("users.txt");
        ArrayList<Cuisine> cuisines = FileManager.loadCuisines("cuisines.txt");
        
        boolean updateSuccess;
        
        if (uid.startsWith("V")) {
            String cuisineType = JOptionPane.showInputDialog(null, "Please enter the cuisine type:", "Cuisine Type", JOptionPane.QUESTION_MESSAGE);
            
            if (cuisineType != null && !cuisineType.trim().isEmpty()) {
                admin.updateCuisine(cuisines, uid, newUsername, cuisineType);
                updateSuccess = admin.updateUser(users, uid, newUsername, newPassword, newbalance);
                FileManager.writeCuisines("cuisines.txt", cuisines);
            } else {
                JOptionPane.showMessageDialog(null, "Cuisine type cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else {
            updateSuccess = admin.updateUser(users, uid, newUsername, newPassword, newbalance);
        }
        
        if (updateSuccess) {
            FileManager.writeUsers("users.txt", users);
            JOptionPane.showMessageDialog(null, "User updated sucessfully!", "Sucess", JOptionPane.INFORMATION_MESSAGE);
            updateUserList("");
            selectedUserField.setText("");
            newUsernametxt.setText("");
            newPasswordtxt.setText("");
            newBalance.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "User not found", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void selectedUserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedUserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedUserFieldActionPerformed

    // Display all users at the start of program
    public void updateUserList(String query) {
        
        ArrayList<User> users = FileManager.loadUsers("users.txt");
        ArrayList<String> displayUsers = new ArrayList<>();
        
        for (User user : users) {
            String userDisplay = user.getUid() + " - " + user.getUsername();
            
            if (query.isEmpty() || userDisplay.toLowerCase().contains(query.toLowerCase())) {
                displayUsers.add(userDisplay);
            }
        }
        userList.setListData(displayUsers.toArray(new String[0]));
    }
    
    private void addUserSelectionListener() {
        
        userList.addListSelectionListener(listener -> {
            if (!listener.getValueIsAdjusting() && userList.getSelectedValue() != null) {
                String selectedUser = userList.getSelectedValue();
                String selectedUID = selectedUser.split(" - ")[0];
                
                ArrayList<User> users = FileManager.loadUsers("users.txt");
                for (User user : users) {
                    if (user.getUid().equals(selectedUID)) {
                        selectedUserField.setText(selectedUser);
                        selectedUserField.setEditable(false);
                        newUsernametxt.setText(user.getUsername());
                        newPasswordtxt.setText(user.getPassword());
                        newBalance.setText(String.valueOf(user.getBalance()));
                        break;
                    }
                }
            }
        });
    }
    
    private void addSearchFieldListener() {                                         
        searchField.getDocument().addDocumentListener(new DocumentListener() {
            
            @Override
            public void insertUpdate(DocumentEvent e){
                updateUserList(searchField.getText().trim());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateUserList(searchField.getText().trim());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateUserList(searchField.getText().trim());
            }
        });  
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateUserFrame frame = new UpdateUserFrame();
                frame.setVisible(true);
                frame.updateUserList("");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField newBalance;
    private javax.swing.JTextField newPasswordtxt;
    private javax.swing.JTextField newUsernametxt;
    private javax.swing.JButton returnButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JFormattedTextField selectedUserField;
    private javax.swing.JButton updateButton;
    private javax.swing.JList<String> userList;
    // End of variables declaration//GEN-END:variables
}
